In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
df=pd.read_csv(r'C:\Users\hp\Downloads\archive (1)\WTD.csv')

In [3]:
df

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,Row0,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0
1,Row1,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0
2,Row2,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0
3,Row3,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,55.0,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0
4,Row4,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,48.0,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99511,Row101816,Uluru,8.0,20.7,0.0,NaN,NaN,ESE,41.0,SE,...,56.0,32.0,1028.1,1024.3,NaN,7.0,11.6,20.0,No,0
99512,Row101817,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,59.0,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,No,0
99513,Row101818,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,0
99514,Row101819,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,0
99515,Row101820,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,0

In [4]:
df.head()

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,Row0,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0
1,Row1,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0
2,Row2,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0
3,Row3,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,55.0,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0
4,Row4,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,48.0,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,0

In [5]:
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainTomorrow
count,99073.000000,99286.000000,98537.000000,56985.00000,52199.000000,93036.000000,98581.000000,97681.000000,98283.000000,97010.000000,89768.000000,89780.000000,61944.000000,59514.000000,98902.000000,97612.000000,99516.000000
mean,12.176266,23.218513,2.353024,5.46132,7.615090,39.976966,14.004849,18.650464,68.866376,51.433296,1017.684638,1015.286204,4.447985,4.519122,16.970041,21.681340,0.224677
std,6.390882,7.115072,8.487866,4.16249,3.783008,13.581524,8.902323,8.801827,19.074951,20.777616,7.110166,7.045189,2.886580,2.716618,6.488961,6.931681,0.417372
min,-8.500000,-4.100000,0.000000,0.00000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.500000,978.200000,0.000000,0.000000,-7.000000,-5.100000,0.000000
25%,7.600000,17.900000,0.000000,2.60000,4.800000,31.000000,7.000000,13.000000,57.000000,37.000000,1013.000000,1010.500000,1.000000,2.000000,12.300000,16.600000,0.000000
50%,12.000000,22.600000,0.000000,4.80000,8.400000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.700000,1015.300000,5.000000,5.000000,16.700000,21.100000,0.000000
75%,16.800000,28.200000,0.800000,7.40000,10.600000,48.000000,19.000000,24.000000,83.000000,65.000000,1022.400000,1020.000000,7.000000,7.000000,21.500000,26.400000,0.000000
max,33.900000,48.100000,371.000000,86.20000,14.500000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,1.000000

In [6]:
print(df.count().sort_values())

Sunshine         52199
Evaporation      56985
Cloud3pm         59514
Cloud9am         61944
Pressure9am      89768
Pressure3pm      89780
WindDir9am       92510
WindGustDir      92995
WindGustSpeed    93036
WindDir3pm       96868
Humidity3pm      97010
Temp3pm          97612
WindSpeed3pm     97681
Humidity9am      98283
Rainfall         98537
RainToday        98537
WindSpeed9am     98581
Temp9am          98902
MinTemp          99073
MaxTemp          99286
row ID           99516
Location         99516
RainTomorrow     99516
dtype: int64

In [7]:
df = df.drop(columns = ['Sunshine','WindGustDir','WindDir9am','WindDir3pm','Evaporation','row ID','Location','Cloud9am','Cloud3pm'])

In [8]:
df

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0
2,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0
3,14.6,29.7,0.2,56.0,19.0,24.0,55.0,23.0,1009.2,1005.4,20.6,28.9,No,0
4,7.7,26.7,0.0,35.0,6.0,17.0,48.0,19.0,1013.4,1010.1,16.3,25.5,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99511,8.0,20.7,0.0,41.0,19.0,26.0,56.0,32.0,1028.1,1024.3,11.6,20.0,No,0
99512,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,0
99513,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,0
99514,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,0
99515,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,0

In [9]:
print(df.shape)

(99516, 14)

In [10]:
df.isnull().sum()

MinTemp           443
MaxTemp           230
Rainfall          979
WindGustSpeed    6480
WindSpeed9am      935
WindSpeed3pm     1835
Humidity9am      1233
Humidity3pm      2506
Pressure9am      9748
Pressure3pm      9736
Temp9am           614
Temp3pm          1904
RainToday         979
RainTomorrow        0
dtype: int64

In [11]:
print(df.shape)

(99516, 14)

In [12]:
df = df.dropna(how = 'any')
print(df.shape)

(83809, 14)

In [13]:
df

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0
2,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0
3,14.6,29.7,0.2,56.0,19.0,24.0,55.0,23.0,1009.2,1005.4,20.6,28.9,No,0
4,7.7,26.7,0.0,35.0,6.0,17.0,48.0,19.0,1013.4,1010.1,16.3,25.5,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99511,8.0,20.7,0.0,41.0,19.0,26.0,56.0,32.0,1028.1,1024.3,11.6,20.0,No,0
99512,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,0
99513,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,0
99514,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,0
99515,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,0

In [14]:
from scipy import stats
z = np.abs(stats.zscore(df._get_numeric_data()))
print(z)

[[0.16203185 0.08122797 0.20450017 ... 0.04059344 0.0235896  0.53038369]
 [0.78243128 0.23370238 0.27574624 ... 0.0059632  0.34254438 0.53038369]
 [0.80741498 1.26438351 0.15700279 ... 0.09907648 1.13339379 0.53038369]
 ...
 [1.50651968 0.00965289 0.27574624 ... 1.09587722 0.06428255 0.53038369]
 [1.38059126 0.26233241 0.27574624 ... 0.97172619 0.3718351  0.53038369]
 [1.09725232 0.49137266 0.27574624 ... 0.72342412 0.60616085 0.53038369]]

In [15]:
df = df[(z<3).all(axis=1)]
print(df.shape)

(80180, 14)

In [16]:
df

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0
2,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0
3,14.6,29.7,0.2,56.0,19.0,24.0,55.0,23.0,1009.2,1005.4,20.6,28.9,No,0
4,7.7,26.7,0.0,35.0,6.0,17.0,48.0,19.0,1013.4,1010.1,16.3,25.5,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99511,8.0,20.7,0.0,41.0,19.0,26.0,56.0,32.0,1028.1,1024.3,11.6,20.0,No,0
99512,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,0
99513,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,0
99514,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,0
99515,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,0

In [17]:
df['RainToday'] = df['RainToday'].map({'No':0, 'Yes':1})

C:\Users\hp\AppData\Local\Temp\ipykernel_11788\3423870996.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RainToday'] = df['RainToday'].map({'No':0, 'Yes':1})

In [18]:
df

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,0,0
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,0,0
2,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,0,0
3,14.6,29.7,0.2,56.0,19.0,24.0,55.0,23.0,1009.2,1005.4,20.6,28.9,0,0
4,7.7,26.7,0.0,35.0,6.0,17.0,48.0,19.0,1013.4,1010.1,16.3,25.5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99511,8.0,20.7,0.0,41.0,19.0,26.0,56.0,32.0,1028.1,1024.3,11.6,20.0,0,0
99512,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,0,0
99513,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,0,0
99514,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,0,0
99515,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,0,0

In [19]:
df['RainToday'].unique()

array([0, 1])

In [20]:
df['Rainfall'].unique()

array([ 0.6,  0. ,  1. ,  0.2,  1.4,  2.2,  3.6, 16.8, 10.6,  1.2,  6.4,
        3. ,  5.8,  0.4,  1.8,  8.4, 20. , 21. ,  3.2,  4.8,  4.2,  0.8,
        8. , 14.4,  4.6,  2. ,  5.6,  1.6,  6. ,  5.4,  5. ,  7.8,  6.8,
        9.8,  2.4,  5.2,  6.6,  3.8, 13.4, 10.2,  7. ,  9.4,  8.6, 11. ,
       21.4,  6.2,  7.2,  8.2, 10.8, 15.4,  4. , 21.8, 24.8, 11.4, 19. ,
        3.4, 19.2, 18.8, 14.8, 18.4, 25.6, 13.8, 12.2, 12.8, 19.8, 17.4,
        8.8,  2.6,  4.4, 16.2,  2.8, 16.6,  9. , 27.2, 14.2, 11.2, 24.6,
       12.6, 10.4,  7.4, 16. , 19.4, 17.2, 13. ,  9.2, 12.4, 15. ,  7.6,
        9.6, 27. , 13.2, 15.8, 14.6, 11.6, 16.4, 15.2, 23. , 22.8, 10. ,
       15.6, 24.2, 12. , 22. , 17. , 18. , 18.6, 23.4, 13.6, 20.8, 25.4,
       14. , 25.8, 20.4, 18.2, 24. , 11.8, 22.6, 21.6, 26. , 22.4, 27.4,
        1.3, 23.6, 24.4, 21.2, 20.2, 19.6, 23.8, 26.8, 17.8,  5.5, 25.2,
       25. ,  0.9,  0.3,  1.7,  3.3, 22.2,  8.5,  0.1,  0.7, 10.1, 17.6,
        3.1,  1.5,  3.5, 26.4,  0.5,  2.7, 13.9, 26.6, 20.6, 22.7,  2.9,
       20.9, 23.2, 26.2,  2.1,  1.9,  4.7,  1.1,  5.7,  4.5, 12.3, 22.9,
        8.7,  2.5,  4.9, 11.9,  9.5,  2.3, 10.5,  6.1,  3.9,  6.7,  6.3,
       12.7,  7.1,  6.5,  8.9, 12.5, 12.1,  7.5,  7.9, 25.3,  7.3])

In [21]:
categorical_columns = ['WindGustSpeed','WindSpeed9am','WindSpeed3pm']
for col in categorical_columns:
    print(np.unique(df[col]))

[ 6.  7.  9. 11. 13. 15. 17. 19. 20. 22. 24. 26. 28. 30. 31. 33. 35. 37.
 39. 41. 43. 44. 46. 48. 50. 52. 54. 56. 57. 59. 61. 63. 65. 67. 69. 70.
 72. 74. 76. 78. 80.]
[ 0.  2.  4.  6.  7.  9. 11. 13. 15. 17. 19. 20. 22. 24. 26. 28. 30. 31.
 33. 35. 37. 39.]
[ 0.  2.  4.  6.  7.  9. 11. 13. 15. 17. 19. 20. 22. 24. 26. 28. 30. 31.
 33. 35. 37. 39. 41. 43. 44.]

In [22]:
df = pd.get_dummies(df, columns = categorical_columns)
print(df.iloc[4:9])

   MinTemp  MaxTemp  Rainfall  Humidity9am  Humidity3pm  Pressure9am  \
4      7.7     26.7       0.0         48.0         19.0       1013.4
5     13.1     30.1       1.4         58.0         27.0       1007.0
6     13.4     30.4       0.0         48.0         22.0       1011.8
7     15.9     21.7       2.2         89.0         91.0       1010.5
8     12.6     21.0       3.6         65.0         43.0       1001.2

   Pressure3pm  Temp9am  Temp3pm  RainToday  ...  WindSpeed3pm_28.0  \
4       1010.1     16.3     25.5          0  ...              False
5       1005.7     20.1     28.2          1  ...              False
6       1008.7     20.4     28.8          0  ...              False
7       1004.2     15.9     17.0          1  ...              False
8       1001.8     15.8     19.8          1  ...              False

   WindSpeed3pm_30.0  WindSpeed3pm_31.0  WindSpeed3pm_33.0  WindSpeed3pm_35.0  \
4              False              False              False              False
5              False              False              False              False
6              False              False              False              False
7              False              False              False              False
8              False              False              False              False

   WindSpeed3pm_37.0  WindSpeed3pm_39.0  WindSpeed3pm_41.0  WindSpeed3pm_43.0  \
4              False              False              False              False
5              False              False              False              False
6              False              False              False              False
7              False              False              False              False
8              False              False              False              False

   WindSpeed3pm_44.0
4              False
5              False
6              False
7              False
8              False

[5 rows x 99 columns]

In [23]:
df

,MinTemp,MaxTemp,Rainfall,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,...,WindSpeed3pm_28.0,WindSpeed3pm_30.0,WindSpeed3pm_31.0,WindSpeed3pm_33.0,WindSpeed3pm_35.0,WindSpeed3pm_37.0,WindSpeed3pm_39.0,WindSpeed3pm_41.0,WindSpeed3pm_43.0,WindSpeed3pm_44.0
0,13.4,22.9,0.6,71.0,22.0,1007.7,1007.1,16.9,21.8,0,...,False,False,False,False,False,False,False,False,False,False
1,7.4,25.1,0.0,44.0,25.0,1010.6,1007.8,17.2,24.3,0,...,False,False,False,False,False,False,False,False,False,False
2,17.5,32.3,1.0,82.0,33.0,1010.8,1006.0,17.8,29.7,0,...,False,False,False,False,False,False,False,False,False,False
3,14.6,29.7,0.2,55.0,23.0,1009.2,1005.4,20.6,28.9,0,...,False,False,False,False,False,False,False,False,False,False
4,7.7,26.7,0.0,48.0,19.0,1013.4,1010.1,16.3,25.5,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99511,8.0,20.7,0.0,56.0,32.0,1028.1,1024.3,11.6,20.0,0,...,False,False,False,False,False,False,False,False,False,False
99512,3.5,21.8,0.0,59.0,27.0,1024.7,1021.2,9.4,20.9,0,...,False,False,False,False,False,False,False,False,False,False
99513,2.8,23.4,0.0,51.0,24.0,1024.6,1020.3,10.1,22.4,0,...,False,False,False,False,False,False,False,False,False,False
99514,3.6,25.3,0.0,56.0,21.0,1023.5,1019.1,10.9,24.5,0,...,False,False,False,False,False,False,False,False,False,False
99515,5.4,26.9,0.0,53.0,24.0,1021.0,1016.8,12.5,26.1,0,...,False,False,False,False,False,False,False,False,False,False

In [24]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
scaler.fit(df)
df = pd.DataFrame(scaler.transform(df), index=df.index, columns = df.columns)
print(df.iloc[4:10])

     MinTemp   MaxTemp  Rainfall  Humidity9am  Humidity3pm  Pressure9am  \
4   0.371353  0.576555  0.000000     0.415730         0.19     0.400000
5   0.514589  0.657895  0.051095     0.528090         0.27     0.249412
6   0.522546  0.665072  0.000000     0.415730         0.22     0.362353
7   0.588859  0.456938  0.080292     0.876404         0.91     0.331765
8   0.501326  0.440191  0.131387     0.606742         0.43     0.112941
10  0.541114  0.437799  0.000000     0.651685         0.82     0.371765

    Pressure3pm   Temp9am   Temp3pm  RainToday  ...  WindSpeed3pm_28.0  \
4      0.377672  0.472441  0.578554        0.0  ...                0.0
5      0.273159  0.572178  0.645885        1.0  ...                0.0
6      0.344418  0.580052  0.660848        0.0  ...                0.0
7      0.237530  0.461942  0.366584        1.0  ...                0.0
8      0.180523  0.459318  0.436409        1.0  ...                0.0
10     0.384798  0.496063  0.394015        0.0  ...                0.0

    WindSpeed3pm_30.0  WindSpeed3pm_31.0  WindSpeed3pm_33.0  \
4                 0.0                0.0                0.0
5                 0.0                0.0                0.0
6                 0.0                0.0                0.0
7                 0.0                0.0                0.0
8                 0.0                0.0                0.0
10                0.0                0.0                0.0

    WindSpeed3pm_35.0  WindSpeed3pm_37.0  WindSpeed3pm_39.0  \
4                 0.0                0.0                0.0
5                 0.0                0.0                0.0
6                 0.0                0.0                0.0
7                 0.0                0.0                0.0
8                 0.0                0.0                0.0
10                0.0                0.0                0.0

    WindSpeed3pm_41.0  WindSpeed3pm_43.0  WindSpeed3pm_44.0
4                 0.0                0.0                0.0
5                 0.0                0.0                0.0
6                 0.0                0.0                0.0
7                 0.0                0.0                0.0
8                 0.0                0.0                0.0
10                0.0                0.0                0.0

[6 rows x 99 columns]

In [25]:
from sklearn.feature_selection import SelectKBest, chi2

x = df.loc[:, df.columns != 'RainTomorrow']
y = df['RainTomorrow']

selector = SelectKBest(score_func=chi2, k=3)

selector.fit(x, y)

x_new = selector.transform(x)

print(x.columns[selector.get_support(indices=True)])

Index(['Rainfall', 'Humidity3pm', 'RainToday'], dtype='object')

In [26]:
df = df[['Rainfall', 'Humidity3pm', 'RainToday','RainTomorrow']]
x = df[['Humidity3pm']]
y = df[['RainTomorrow']]

In [27]:
# data Modeling 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import time

In [28]:
t0=time.time()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
clf_logreg = LogisticRegression(random_state = 0)
clf_logreg.fit(x_train,y_train)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(random_state=0)

In [29]:
y_pred = clf_logreg.predict(x_test)
score = accuracy_score(y_test,y_pred)

In [30]:
print(score)
print(time.time()-t0)

0.8366176103766525
0.0947122573852539

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [32]:
t0 = time.time()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)
clf_rf = RandomForestClassifier(n_estimators = 100 , max_depth = 4 , random_state = 0)

In [33]:
clf_rf.fit(x_train,y_train)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(max_depth=4, random_state=0)

In [34]:
y_prep = clf_rf.predict(x_test)
score = accuracy_score(y_test,y_pred)

In [35]:
print(score)
print(time.time()-t0)

0.7310551259665752
1.2494165897369385

In [36]:
#decision tree classifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [37]:
t0 = time.time()
x_train,x_test,y_train,y_test = train_test_split (x,y,test_size = 0.25)
clf_dt = DecisionTreeClassifier(random_state = 0)

In [38]:
clf_dt.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [39]:
y_pred = clf_dt.predict(x_test)
score = accuracy_score(y_test,y_pred)

In [40]:
print(score)
print(time.time()-t0)

0.8354203043152906
0.08649396896362305

In [41]:
from sklearn import svm
from sklearn.model_selection import train_test_split

t0 = time.time()

In [42]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25)
clf_svc = svm.SVC(kernel='linear')

In [43]:
clf_svc.fit(x_train,y_train)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(kernel='linear')

In [44]:
y_pred =clf_svc.predict(x_test)
score = accuracy_score(y_test,y_pred)

In [45]:
print(score)
print(time.time()-t0)

0.7972062858568222
64.15238928794861

In [46]:
df

       Rainfall  Humidity3pm  RainToday  RainTomorrow
0      0.021898         0.22        0.0           0.0
1      0.000000         0.25        0.0           0.0
2      0.036496         0.33        0.0           0.0
3      0.007299         0.23        0.0           0.0
4      0.000000         0.19        0.0           0.0
...         ...          ...        ...           ...
99511  0.000000         0.32        0.0           0.0
99512  0.000000         0.27        0.0           0.0
99513  0.000000         0.24        0.0           0.0
99514  0.000000         0.21        0.0           0.0
99515  0.000000         0.24        0.0           0.0

[80180 rows x 4 columns]